name: Validate JSONs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: npm ci
      - name: Validate JSON
        run: npm test
